export const ADD_TO_CHECKED_CARD = "ADD_TO_CHECKED_CARD";
export const CLEAR_CHECKED_CARD = "CLEAR_CHECKED_CARD";
export const USER_CAN_CLICK_ON = "USER_CAN_CLICK_ON";
export const USER_CAN_CLICK_OFF = "USER_CAN_CLICK_OFF";
