export const HAND_OUT_CARDS = 'HAND_OUT_CARDS';
export const COMPARE_CARDS = 'COMPARE_CARDS';
export const ADD_FLIPP = 'ADD_FLIPP';
export const CHECK_CARDS_COUNT = 'CHECK_CARDS_COUNT';
export const ANIMATION_PAUSE = 1000;
export const REDIRECT_TO_WINNER_COMPONENT = "REDIRECT_TO_WINNER_COMPONENT";
