export const SAVE_SCORE_REQUEST = "SAVE_SCORE_REQUEST";
export const SAVE_SCORE_REQUEST_FAILED = "SAVE_SCORE_REQUEST_FAILED";
export const SCORE_SAVED = "SCORE_SAVED";
export const CLEAR_SCORE_MESSAGE = "CLEAR_SCORE_MESSAGE";
